theming dark mode fashion buttons fixed
OntimizeWeb/ontimize-web-ngx-theming pull request #94
Opened 2023-02-06 11:08 UTC by javierFernandezMendez

2023-02-06 14:08 UTC, daniel-grana approved these changes

2023-02-07 09:21 UTC, daniel-grana approved these changes

2023-02-07 12:44 UTC, patricia-martinez-imatia requested changes

2023-02-07 12:44 UTC, patricia-martinez-imatia commented on src/styles/implatform-fashion-theme-styles.scss
> +        color: mat-color($primary, 500);
```suggestion
        color: mat-color($accent, 500);
```

2023-02-08 09:15 UTC, daniel-grana approved these changes

2023-02-08 09:23 UTC, patricia-martinez-imatia approved these changes

2023-02-08 11:01 UTC, merged